[tool.poetry]
name = "miniexcel"
version = "0.1.0"
description = ""
authors = ["nadezhdaSwan <nalebedevawork@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.1"
wxpython = "4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
